// Generated by CoffeeScript 1.3.1
var RequestAdapter;

global.window = {};

require('../../vendor/inflection/inflection.js');

delete global.window;

RequestAdapter = (function() {

  RequestAdapter.name = 'RequestAdapter';

  function RequestAdapter() {}

  RequestAdapter.request = require('request');

  return RequestAdapter;

})();
