// Generated by CoffeeScript 1.3.1
var NodejsRequestAdapter;

NodejsRequestAdapter = (function() {

  NodejsRequestAdapter.name = 'NodejsRequestAdapter';

  function NodejsRequestAdapter() {
    this.request = require('request');
  }

  return NodejsRequestAdapter;

})();
